# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: TackemTesting
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
    - CGO_ENABLED=0
  - goos:
    - linux
  - goarch:
    - amd64
  - goamd64:
    - v1
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}'
