project_name: TackemTesting
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  -
    id: build
    binary: "{{ .ProjectName}}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
    ldflags:
      # - "-s -w -X serviceController.Version={{.Version}} -X serviceController.Commit={{.Commit}} -X serviceController.CommitDate={{.Date}}"
      - "-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.CommitDate={{.Date}}"
archives:
  -
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
snapshot:
  name_template: '{{ incpatch  .Version }}-devel'
# dockers:
# - image_templates:
#     - "ghcr.io/Tackem-org/Testing:latest"
#     - "ghcr.io/Tackem-org/Testing:{{ .Version }}"
#     - "ghcr.io/Tackem-org/Testing:{{ .Major }}"
#     - "ghcr.io/Tackem-org/Testing:{{ .Major }}.{{.Minor}}"
#   dockerfile: goreleaser.dockerfile
#   build_flag_templates:
#   - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#   - "--label=org.opencontainers.image.description={{ .ProjectName }}"
#   - "--label=org.opencontainers.image.url=https://github.com/Tackem-org/Testing"
#   - "--label=org.opencontainers.image.source=https://github.com/Tackem-org/Testing"
#   - "--label=org.opencontainers.image.version={{ .Version }}"
#   - "--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}"
#   - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#   - "--label=org.opencontainers.image.licenses=GPLv2"
#   - "--platform={{ .Os }}/{{ .Arch }}"
# nfpms:
# - maintainer: Gary The Brown <garybrownsunderland@gmail.com>
#   description: Test project.
#   homepage: https://github.com/Tackem-org/Testing
#   license: GPLv2
#   formats:
#   - deb
#   - rpm
#   - apk
